### ISSUE TITLE
Extending client number

### ISSUE THREAD

**Issue by Muhammadkamrul** [FREDERICO23/Churn--Federated-Learning-#1]
Dear author, Thanks for your excellent work. I need your suggestion on how can I extend client number? For example if I want 10 clients to join for this Federated learning, what modification should I do and where? Thank you.

**Comment by FREDERICO23** [comment]
In the `server.py` file in the main function, update this line of code:

```python
if __name__ == "__main__":
    ...
    min_available_clients=10,
    ...
```

**Comment by Muhammadkamrul** [comment]
> In the `server.py` file in the main function, update this line of code:
> 
> ```python
> if __name__ == "__main__":
>     ...
>     min_available_clients=10,
>     ...
> ```

Thanks a million!
